version: '3'
services:
  lagom-with-seed:
    image: roller-impl:1.0-SNAPSHOT
    ports:
      - "9000:9000"
      - "9095:9095"
    environment:
      - DB_HOST_IP=192.168.0.126
      - BIND_IP=0.0.0.0
      - BIND_PORT=2551
      - KAFKA_HOST_IP_AND_PORT=192.168.1.244:9092
      - FIRST_HOST_IP=lagom-with-seed
      - FIRST_HOST_PORT=2551
      - SECOND_HOST_IP=lagom-with-seed-1
      - SECOND_HOST_PORT=2552 
      - HOST_IP=lagom-with-seed
      - HOST_PORT=2551
    networks:
      - justicenetwork
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
  lagom-with-seed-1:
    image: roller-impl:1.0-SNAPSHOT
    ports:
      - "9001:9000"
      - "9096:9095"
    environment:
      - DB_HOST_IP=192.168.0.126
      - BIND_IP=0.0.0.0
      - BIND_PORT=2552
      - KAFKA_HOST_IP_AND_PORT=192.168.1.244:9092
      - FIRST_HOST_IP=lagom-with-seed
      - FIRST_HOST_PORT=2551
      - SECOND_HOST_IP=lagom-with-seed-1
      - SECOND_HOST_PORT=2552
      - HOST_IP=lagom-with-seed-1
      - HOST_PORT=2552
    networks:
      - justicenetwork
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 20s
        max_attempts: 3
        window: 120s
networks:
  justicenetwork:
